spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/restkeycloakproject
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:8080/realms/securityKeyCloak
         jwk-set-uri: http://localhost:8080/realms/securityKeyCloak/protocol/openid-connect/certs
server:
  port: 8082



